CREATE TABLE T_HEADER
(
  HEADER_ID NUMBER(15,0) PRIMARY KEY NOT NULL,
  TLSZ NUMBER(4,0) NOT NULL,
  SUM NUMBER(4,0) NOT NULL
);
CREATE TABLE T_WORK_DATA
(
  WORK_DATA_ID NUMBER(15,0) PRIMARY KEY NOT NULL,
  MK NUMBER(2,0) NOT NULL,
  WORKER NUMBER(3,0),
  DB NUMBER(4,0),
  NORM NUMBER(4,0) NOT NULL,
  HEADER_ID NUMBER(15,0) NOT NULL
);
ALTER TABLE T_WORK_DATA ADD FOREIGN KEY (HEADER_ID) REFERENCES T_HEADER (HEADER_ID);

CREATE TABLE CSASZI.T_TLSZ_MK_N_MAP
(
  TLSZ NUMBER(3) NOT NULL,
  MK NUMBER(3) NOT NULL,
  NORM NUMBER(4) NOT NULL,
  PRIMARY KEY (TLSZ, MK, NORM)
);
ALTER TABLE "CSASZI"."T_WORK_DATA" ADD CONSTRAINT unique_row UNIQUE("MK","WORKER","DB","NORM","HEADER_ID");
